glslangValidator.exe -V D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\compute1.comp -o D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\compute1.spv
glslangValidator.exe -V D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\compute2.comp -o D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\compute2.spv
glslangValidator.exe -V D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\compute3.comp -o D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\compute3.spv
glslangValidator.exe -V D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\compute4.comp -o D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\compute4.spv
glslangValidator.exe -V D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\compute5.comp -o D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\compute5.spv
glslangValidator.exe -V D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw1.vert -o D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw1.vert.spv
glslangValidator.exe -V D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw1.frag -o D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw1.frag.spv
glslangValidator.exe -V D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw2.vert -o D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw2.vert.spv
glslangValidator.exe -V D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw2.frag -o D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw2.frag.spv
glslangValidator.exe -V D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw3.vert -o D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw3.vert.spv
glslangValidator.exe -V D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw3.frag -o D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw3.frag.spv
glslangValidator.exe -V D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw4.vert -o D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw4.vert.spv
glslangValidator.exe -V D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw4.frag -o D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw4.frag.spv
glslangValidator.exe -V D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw5.vert -o D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw5.vert.spv
glslangValidator.exe -V D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw5.frag -o D:\gitrepos\VulkanScene\Vulkan\shaders\glsl\vulkanscene\draw5.frag.spv
