#version 450
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

layout (local_size_x = 32, local_size_y = 1) in;

layout(push_constant) uniform PushConstants {
   uint srcOffset;
   uint dstOffset;
   uint size;
   float temp1;
   float temp2;
   float temp3;
   float temp4;
} pushConstants;


layout(std430, binding=0) buffer ReadData {
    uint inData[];
};

layout(std430, binding=1) buffer WriteData {
    uint outData[];
};


void main()
{
    uint idx = gl_GlobalInvocationID.x;
    if (idx < pushConstants.size) {
        outData[pushConstants.dstOffset + idx] = inData[pushConstants.srcOffset + idx];
    }
}
